### ISSUE TITLE
RuntimeException Invalid Signature

### ISSUE THREAD

**Issue by hrach** [juzna/intellij-nette#23]
```
Invalid Signature #M#ȣeventsƀ\Signaly\Posts\PostManagerƀ#ȣormƀ\Signaly\Posts\PostManagerƀ\Signaly\Posts\PostManager
java.lang.RuntimeException: Invalid Signature #M#ȣeventsƀ\Signaly\Posts\PostManagerƀ#ȣormƀ\Signaly\Posts\PostManagerƀ\Signaly\Posts\PostManager
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:385)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:302)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:292)
	at cz.juzna.intellij.nette.utils.PhpIndexUtil.getBySignature(PhpIndexUtil.java:24)
	at cz.juzna.intellij.nette.utils.PhpIndexUtil.getByType(PhpIndexUtil.java:42)
	at cz.juzna.intellij.nette.typeProvider.NetteObjectFieldsTypeProvider.getBySignature(NetteObjectFieldsTypeProvider.java:65)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:416)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:302)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:79)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.globalLocationAware(PhpType.java:395)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:143)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:144)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:136)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:122)
	at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.inspect(PhpMethodParametersCountMismatchInspection.java:40)
	at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.visitPhpMethodReference(PhpMethodParametersCountMismatchInspection.java:94)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:29)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by matej21** [comment]
Is it reproducible? Are you able to isolate the failing code?

**Comment by hrach** [comment]
Probably not. It's great project and I noticed it after a while.

**Comment by hrach** [comment]
Thanks! Great!
